### ISSUE TITLE
Exons and introns GTF files for `gencode` annotation

### ISSUE THREAD

**Issue by abearab** [csglab/CRIES#3]
Previously, I tried to generate the GTF files from `gencode` annotation but I couldn't fully reproduce the idea here. Looking at the new [generate_const_intronsExons_gtf.R](https://github.com/rached-97/CRIES/blob/master/generate_const_intronsExons_gtf.R) script, I can see it make much more sense. However, is there any specific reason to use Ensembl, not gencode?

**Comment by hsnajafabadi** [comment]
The idea should be applicable to Gencode annotations, with some modifications. One issue would be the set of exons that are considered when the script tries to identify constitutive exons. Currently, the script uses exons with "source == 'ensembl_havana'"; this tag is not available in the Gencode GTF files.

**Comment by abearab** [comment]
Thanks for explaining, sir.
